import{S as L,i as c,a as S}from"./assets/vendor-5401a4b0.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const h="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEaSURBVHgBrZZhDoIwDIUL0fjXo3gUb7R5Er0BHsXD7A+bASlhYeC6V4WXGCHr3reNtkAkqG2D9T70mh/HSj4HybyqyPQ9PeuaXlRQ19GFY4c5dDodLSHNK3/fSam29Q+0k7/N1ZAt5hCyh7kIKZl77y/IMBezgEwXTW4ienBxcc65DCQ0PDYCQghGMDASJJpzTG4ue0KABEHmKeBAQEPx3LiIhmKy/M+aitDyGJoPAWsI32vNWTXpVQnXRal2kPQmO7pPx6XpPRCQmsdjSZ8JhIA0FbOllMKsRZqCQoMpXCy0GJRrFc7hVpGLSVqFWaxk52ZnVgPbIaL5HhBovgVSMv+qg7kt9JznZ+VL//pL+5hWFXei+mwRj+UDSHQ9vnHBEYAAAAAASUVORK5CYII=",v=document.querySelector(".form"),a=document.querySelector(".gallery"),d=document.querySelector(".preload"),l=document.querySelector(".load-more-btn"),u=new L(".gallery a",{captionsData:"alt",captionDelay:250}),w=40;let p=1;v.addEventListener("submit",C);l.addEventListener("click",E);async function C(t){t.preventDefault();const s=t.currentTarget.elements.input.value;if(a.innerHTML="",!s.trim()){c.show({title:"❕",theme:"light",message:"Please, fill in the search field",messageSize:"20px",messageColor:"#808080",backgroundColor:"#e7fc44",position:"topLeft",timeout:3e3});return}d.classList.remove("is-hidden"),l.classList.add("is-hidden");try{const o=await m(s);o.hits.length===0?c.show({iconUrl:h,theme:"dark",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",timeout:5e3}):(a.innerHTML=g(o.hits),u.refresh(),l.classList.remove("is-hidden"))}catch(o){A(o)}finally{d.classList.add("is-hidden")}t.currentTarget.reset()}async function m(t,s=1){const o="https://pixabay.com/api/",i="41989541-8f5a4609d6994378f5ee88908";try{return(await S.get(o,{params:{key:i,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:w}})).data}catch(e){throw new Error(e.message)}}function g(t){t.forEach(({webformatURL:s,largeImageURL:o,tags:i,likes:e,views:r,comments:n,downloads:f})=>{const y=`
      <li class="gallery-item">
        <a class="gallery-link" href="${o}">
          <img class="gallery-image" src="${s}" alt="${i}" />
        </a>
        <div class="container-additional-info">
          <div class="container-descr-inner"><p class="description">Likes</p><span class="description-value">${e}</span></div>
          <div class="container-descr-inner"><p class="description">Views</p><span class="description-value">${r}</span></div>
          <div class="container-descr-inner"><p class="description">Comments</p><span class="description-value">${n}</span></div>
          <div class="container-descr-inner"><p class="description">Downloads</p><span class="description-value">${f}</span></div>
        </div>
      </li>`;a.insertAdjacentHTML("beforeend",y)})}async function E(t){p+=1;try{const s=await m(t.currentTarget.value,p);s.hits.length===0?(document.querySelector(".preload").classList.add("is-hidden"),t.currentTarget.classList.add("is-hidden"),c.show({title:"❕",theme:"light",message:"We're sorry, but you've reached the end of search results.",messageSize:"20px",messageColor:"#808080",backgroundColor:"#e7fc44",position:"topLeft",timeout:5e3})):(a.innerHTML+=g(s.hits),u.refresh(),b())}catch(s){A(s)}}function b(){const t=a.lastElementChild.getBoundingClientRect().height;window.scrollBy(0,t)}function A(t){console.error(t),a.innerHTML="",c.show({iconUrl:h,theme:"dark",message:"Sorry, there is a problem with connection with the server.",messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"center",timeout:5e3})}
//# sourceMappingURL=commonHelpers.js.map
