import{S as y,i as l,a as L}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=i(e);fetch(e.href,s)}})();const u="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEaSURBVHgBrZZhDoIwDIUL0fjXo3gUb7R5Er0BHsXD7A+bASlhYeC6V4WXGCHr3reNtkAkqG2D9T70mh/HSj4HybyqyPQ9PeuaXlRQ19GFY4c5dDodLSHNK3/fSam29Q+0k7/N1ZAt5hCyh7kIKZl77y/IMBezgEwXTW4ienBxcc65DCQ0PDYCQghGMDASJJpzTG4ue0KABEHmKeBAQEPx3LiIhmKy/M+aitDyGJoPAWsI32vNWTXpVQnXRal2kPQmO7pPx6XpPRCQmsdjSZ8JhIA0FbOllMKsRZqCQoMpXCy0GJRrFc7hVpGLSVqFWaxk52ZnVgPbIaL5HhBovgVSMv+qg7kt9JznZ+VL//pL+5hWFXei+mwRj+UDSHQ9vnHBEYAAAAAASUVORK5CYII=",S=document.querySelector(".form"),n=document.querySelector(".gallery"),d=document.querySelector(".preload"),c=document.querySelector(".load-more-btn"),h=new y(".gallery a",{captionsData:"alt",captionDelay:250}),w=40;let p=1;S.addEventListener("submit",v);c.addEventListener("click",C);async function v(r){r.preventDefault();const t=r.currentTarget.elements.input.value;if(n.innerHTML="",!t.trim()){l.show({title:"❕",theme:"light",message:"Please, fill in the search field",messageSize:"20px",messageColor:"#808080",backgroundColor:"#e7fc44",position:"topLeft",timeout:3e3});return}d.classList.remove("is-hidden"),c.classList.add("is-hidden");try{const i=await m(t);i.hits.length===0?l.show({iconUrl:u,theme:"dark",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",timeout:5e3}):(n.innerHTML=g(i.hits),h.refresh(),c.classList.remove("is-hidden"))}catch(i){A(i)}finally{d.classList.add("is-hidden")}c.dataset.query=t,r.currentTarget.reset()}async function m(r,t=1){const i="https://pixabay.com/api/",o="41989541-8f5a4609d6994378f5ee88908";try{return(await L.get(i,{params:{key:o,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:w}})).data}catch(e){throw new Error(e.message)}}function g(r){return r.map(({webformatURL:t,largeImageURL:i,tags:o,likes:e,views:s,comments:a,downloads:f})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${t}" alt="${o}" />
        </a>
        <div class="container-additional-info">
          <div class="container-descr-inner"><p class="description">Likes</p><span class="description-value">${e}</span></div>
          <div class="container-descr-inner"><p class="description">Views</p><span class="description-value">${s}</span></div>
          <div class="container-descr-inner"><p class="description">Comments</p><span class="description-value">${a}</span></div>
          <div class="container-descr-inner"><p class="description">Downloads</p><span class="description-value">${f}</span></div>
        </div>
      </li>`).join("")}async function C(r){p+=1;try{const t=await m(r.currentTarget.dataset.query,p);t.hits.length===0?(document.querySelector(".preload").classList.add("is-hidden"),r.currentTarget.classList.add("is-hidden"),l.show({title:"❕",theme:"light",message:"Вибачте, але ви досягли кінця результатів пошуку.",messageSize:"20px",messageColor:"#808080",backgroundColor:"#e7fc44",position:"topLeft",timeout:5e3})):(n.innerHTML+=g(t.hits),h.refresh(),E())}catch(t){A(t)}}function E(){const r=n.lastElementChild.getBoundingClientRect().height;window.scrollBy(0,r)}function A(r){console.error(r),n.innerHTML="",l.show({iconUrl:u,theme:"dark",message:"Sorry, there is a problem with connection with the server.",messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"center",timeout:5e3})}
//# sourceMappingURL=commonHelpers.js.map
